### PR TITLE
Tidying

### PR DESCRIPTION
**Pull request by alan-jordan**
Have indented the HTML code to make it more readable.

### CODE REVIEW

**Comment by ElenaSchubel** [comment]
Great job on fixing the all the indenting! Really tidy looking :)

**Comment by alan-jordan** [comment]
Thanks @ElenaSchubel Is it good enough to have the pull request merged?

**Comment by sherlyc** [comment]
hi Alan, would me grant me write access? I will accept the pull request for you.

**Comment by alan-jordan** [comment]
Hi @sherlyc I sent you an invite the other day. If you go along here https://github.com/alan-jordan/sprint-2/invitations you should be able to get access.

**Pull request merged**
